---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://api.tfl.gov.uk/Line/Mode/tube,overground,elizabeth-line/Status
polling_headers: ''
polling_body: ''
id: 256159
name: TfL Status 2
refresh_interval: 60
